spring:
  application:
    name: uerekaserver
  security:
    basic:
      enabled: true
    user:
      name: cursoms-eureka-user
      password: cuka-mrsoers-eureus
    
server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  
